{
  _lib,
  lib,
  aiofiles,
  buildPythonApplication,
  hatchling,
  httpx,
  pytestCheckHook,
  vfkit ? null,
  writeText,
}:

let
  inherit (_lib.helpers) toScreamingSnakeCase;
in

buildPythonApplication {
  pname = "virby-vm-runner";
  version = (fromTOML (builtins.readFile ./pyproject.toml)).project.version;

  pyproject = true;
  src = ./.;

  build-system = [ hatchling ];

  dependencies = [
    aiofiles
    httpx
  ]
  ++ lib.optional (vfkit != null) vfkit;

  nativeCheckInputs = [ pytestCheckHook ];

  pythonImportsCheck = [
    "virby_vm_runner"
    "virby_vm_runner.api"
    "virby_vm_runner.circuit_breaker"
    "virby_vm_runner.cli"
    "virby_vm_runner.config"
    "virby_vm_runner.constants"
    "virby_vm_runner.exceptions"
    "virby_vm_runner.ip_discovery"
    "virby_vm_runner.runner"
    "virby_vm_runner.signal_manager"
    "virby_vm_runner.socket_activation"
    "virby_vm_runner.ssh"
    "virby_vm_runner.vm_process"
  ];

  preBuild = ''
    cat ${writeText "constants.py" ''
      """Variable constants for Virby.

      This file was generated by Nix using the variables from `lib/constants.nix`.
      """

      ${lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: value: "${toScreamingSnakeCase name} = \"${value}\"") _lib.constants
      )}
    ''} > src/virby_vm_runner/constants.py
  '';

  meta = {
    description = "Vfkit-based VM runner for Virby";
    homepage = "https://github.com/quinneden/virby-nix-darwin";
    license = lib.licenses.mit;
    platforms = if vfkit == null then lib.platforms.unix else lib.platforms.darwin;
    mainProgram = "virby-vm";
  };
}
